adminapp/urls.py
from django.urls import path
from adminapp import views as adminapp

# с версии 2.0 app_name
app_name = 'adminapp'

urlpatterns = [
    # CRUD
    path('users/create/', adminapp.user_create, name='user_create'),
    # path( 'users/read/' , adminapp.users, name= 'users' ),
    # path('users/read/', adminapp.users, name='users_read'),
    # path('users/read/', adminapp.user_read, name='user_read'),
    # path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/read/', adminapp.UsersListView.as_view(), name='user_read'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    # path('users/update/<int:pk>/', adminapp.UsersUpdateView, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    # path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    # path( 'categories/read/' , adminapp.categories, name= 'categories' ),
    # path('categories/read/', adminapp.categories, name='category_read'),
    path('categories/read/', adminapp.ProductCategoriesListView.as_view(), name='category_read'),
    # path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    # path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    # path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    # Первый выводит список продуктов в категории
    # path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/category/<int:pk>/', adminapp.ProductListView.as_view(), name='products'),
    # а второй — страницу выбранного продукта
    # path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    # path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    # path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path

from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<activation_key>/', authapp.veryfy, name='verify')
]

# теперь создаём контроллер в authapp\view

basketapp/urls.py
from django.urls import path

from basketapp import views as basketapp

# Пятый шаг
# Шестой шаг (включить в geekshop\urls)
# Влияет на namespace
app_name = 'basketapp'

urlpatterns = [
    # Read
    path('', basketapp.basket, name='view'),
    # Create
    # Update
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    # path('add/<int:pk>/', basketapp.BasketUpdateView.as_view(), name='add'),
    # Delete
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from mainapp import views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    # path('products/', mainapp.products, name='products'),
    # include all url is mainapp.urls, т.е. в каждом приложении свои URL, namespace='products' - для использования URL
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', mainapp.contact, name='contact'),

    # ссылка на стандартную админку, переименуем в "control/" для добавления своей админки ниже
    # path('admin/', admin.site.urls),
    # path('control/', admin.site.urls),

    # своя админка namespace='admins' - исключаем конфликт
    # с использованием регулярных выражений re_path для сложных проектов
    # re_path(r'^admin/', include('adminapp.urls', namespace='admin'))
    path('admin/', include('adminapp.urls', namespace='admin')),
    # добавляем модуль "social_django"
    path('', include('social_django.urls', namespace='social')),
    # re_path(r'^order/', include('ordersapp.urls', namespace='order')),
    path('order/', include('ordersapp.urls', namespace='order'))
]

# настройка работает локально
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # подгрузка toolbar
# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path, re_path
from django.views.decorators.cache import cache_page

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    # path('', mainapp.products, name='products'),
    path('', mainapp.products, name='index'),
    # re_path(r'^$', mainapp.products, name='index'),
    # используем для подгрузки категорий "<int:pk>/"
    # path('<int:pk>/', mainapp.products, name='category'),

    path('category/<int:pk>/', mainapp.products, name='category'),

    # re_path(r'^category/(?P<pk>\d+)/$', mainapp.products, name='category'),
    # третий уровень кеширования

    # re_path(r'^category/(?P<pk>\d+)/$', cache_page(3600)(mainapp.products)),

    # re_path(r'^category/(?P<pk>\d+)/ajax/$', cache_page(3600)(mainapp.products_ajax)),

    # один из вариантов написания передачи "page"
    # path('category/<int:pk>/<int:page>', mainapp.products, name='category'),
    # path('category/<int:pk>/<int:page>', mainapp.products, name='page'),

    # re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.product, name='page'),

    # re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/ajax/$', cache_page(3600)(mainapp.products_ajax)),

    # path('<int:pk>/', mainapp.products, name='category'),
    path('product/<int:pk>/', mainapp.product, name='product'),
    # re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),

    # re_path(r'^category/(?P<pk>\d+)/$', mainapp.product, name='product'),

]

ordersapp/urls.py
import ordersapp.views as ordersapp

from django.urls import path, re_path

app_name = 'ordersapp'

urlpatterns = [
    # re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    path('', ordersapp.OrderListView.as_view(), name='orders_list'),
    # re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    path('create/', ordersapp.OrderCreateView.as_view(), name='orders_create'),
    # re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    path('read/<int:pk>/', ordersapp.OrderDetailView.as_view(), name='orders_detail'),
    # re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    path('update/<int:pk>/', ordersapp.OrderUpdateView.as_view(), name='orders_update'),
    # re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),
    path('delete/<int:pk>/', ordersapp.OrderDeleteView.as_view(), name='orders_delete'),

    # re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),
    path('forming/complete/<int:pk>/', ordersapp.order_forming_complete, name='orders_forming_complete'),

    re_path(r'^product/(?P<pk>\d+)/price/$', ordersapp.get_product_price)

]

mainapp/models.py
from django.db import models


# Create your models here.
class ProductCategory(models.Model):
    # При необходимости поле id можно задать в ручную, BigAutoField - для больших значений
    # id = models.BigAutoField(primary_key=True)
    # категории товара = тип товара, поля
    # name - обязательное для заполнения поле
    name = models.CharField(max_length=64, unique=True, verbose_name='имя')
    # описание, если blank=True, то это поле может оставаться пустым и оно не обязательное
    description = models.TextField(verbose_name='описание', blank=True)
    # флаг удаления, не удаляя полностью
    # is_active = models.BooleanField(verbose_name='активность', default=True)
    is_active = models.BooleanField(db_index=True, verbose_name='активность', default=True)

    def __str__(self):
        # '''Преобразование объекта к строке'''
        return self.name


# Один ко многим. models подключается из django.db
class Product(models.Model):
    # "on_delete=" - что делать при удалении? on_delete=models.SET_NULL, blank=True, null=True
    # blank=True и null=True чаще идут в паре и указывают на необязательность заполнения поля
    # models.CASCADE() - каскадное удаление записи из всех таблиц
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=128, verbose_name='имя')
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(max_length=64, verbose_name='краткое описание', blank=True)
    description = models.TextField(blank=True, verbose_name='описание')
    # "max_digits=8" - кол-во знаков до ",", "decimal_places=2" - после
    price = models.DecimalField(verbose_name='цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveSmallIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(db_index=True, verbose_name='активность', default=True)
    # is_active = models.BooleanField(db_index=True, verbose_name='активность', default=True)

    def __str__(self):
        # '''Строковое отображение'''
        return f'{self.name} ({self.category.name})'

    @staticmethod
    def get_items():
        # '''Убираем неактивные продукты с формы'''
        return Product.objects.filter(is_active=True).order_by('category', 'name')

mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
    <li>
        <a href="{% url 'mainapp:category' 0 %}"
           {% if request.resolver_match.kwargs.pk == 0 %}class="active" {% endif %}>
            все
        </a>
    </li>
    {% for link in links_menu %}
        <li>
            {# <a href="{% url 'products:category' link.pk %}">#}
            {#        kwargs - все аргументы передаваемые в url#}

            <a href="{% url 'mainapp:category' link.pk %}"
               {% if request.resolver_match.kwargs.pk == link.pk %}class="active" {% endif %}>
                {#                {{ link.name }} | {{ request.resolver_match.kwargs.pk }}#}
                {{ link.name }}
            </a>
            {#            {% if request.ProductCategory.name is request.Product.category.pk %}True{% endif %}#}
        </li>
    {% endfor %}
</ul>

mainapp/templates/mainapp/includes/inc_main_menu.html
<ul>
    <li>
        <a href="{% url 'main' %}" {% if request.resolver_match.url_name == 'main' %}class="active"{% endif %}>
            домой
        </a>
    </li>
    {# 'products:products' - это <NameSpace>:<Name> #}
    <li>
        <a href="{% url 'products:products' %}"
           {% if 'products' in request.resolver_match.url_name %}class="active"{% endif %}>
            продукты
        </a>
    </li>
    <li>
        <a href="{% url 'contact' %}" {% if request.resolver_match.url_name == 'contact' %}class="active"{% endif %}>
            контакты
        </a>
    </li>
    {% if user.is_authenticated %}
        <li>
            <a href="{% url 'auth:edit' %}">
                {{ user.first_name|default:"Пользователь" }}
            </a>
        </li>
        <li>
            <a href="{% url 'auth:logout' %}">
                выход
            </a>
        </li>
    {% else %}
        <li>
            <a href="{% url 'auth:login' %}">
                вход
            </a>
        </li>
    {% endif %}
</ul>

mainapp/templates/mainapp/includes/inc_menu.html
<a href="{% url 'main' %}" class="logo"></a>
<ul class="menu">
    {#    <ul>#}
    <li>
        <a href="{% url 'main' %}" {% if request.resolver_match.url_name == 'main' %}class="active"{% endif %}>
            домой
        </a>
    </li>
    {# 'products:products' - это <NameSpace>:<Name> #}
    <li>
        {#                <a href="{% url 'products:index' %}"#}
        {#        <a href="{% url 'products:products' %}"#}
        <a href="{% url 'products:index' %}"
           class="{% if request.resolver_match.namespace == 'products' %}active{% endif %}">
            продукты
        </a>
    </li>
    <li>
        <a href="{% url 'contact' %}"
           {% if request.resolver_match.url_name == 'contact' %}class="active"{% endif %}>
            контакты
        </a>
    </li>
    {% if user.is_authenticated %}
        <li>
            <div class="dropdown">
                {#  <a href="{% url 'auth:edit' %}">#}
                {#  {{ user.first_name|default:"Пользователь" }}#}
                {#  {{ user.first_name }}#}
                {#  </a>#}
                <a class="dropdown-toggle" href="" data-toggle="dropdown">
                    {{ user.first_name|default:'Пользователь' }}
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'auth:edit' %}">
                            профиль
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'ordersapp:orders_list' %}">
                            {#                        <a href="#">#}
                            заказы
                        </a>
                    </li>
                </ul>
            </div>
        </li>
    {% endif %}
    {% if user.is_superuser %}
        <li>
            <a href="{% url 'adminapp:user_read' %}">
                админка
                {#                {{ user.first_name }}#}
            </a>
        </li>
    {% endif %}
    <li>
        {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">выход</a>
        {% else %}
            <a href="{% url 'auth:login' %}">вход</a>
        {% endif %}
    </li>
    <li>
        <a href="#" class="search"></a>
    </li>
    <li>
        {#        <a href="{% url 'basket:view' %}" class="basket">#}
        {#                <span>#}
        {#                    {% if basket %}{{ basket|length }}{% endif %}#}
        {#                    {{ basket }}#}
        {#                </span>#}
        {#        </a>#}
        <a href="{% url 'basket:view' %}" class="basket">
                <span>
                    {% if basket %}
                        {# {{ basket.0.total_cost|floatformat:0 }} руб.#}
                        {{ basket.0.get_total_cost|floatformat:0 }} руб.
                        {# ({{ basket.0.total_quantity }} шт.)#}
                        ({{ basket.0.get_total_quantity }} шт.)
                    {% endif %}
                    {#                    {{ basket }}#}
                </span>
        </a>
    </li>
</ul>

mainapp/templates/mainapp/includes/inc_products_list_content.html
{% load static %}

{#<div class="links clearfix">#}
{#    {% include 'mainapp/includes/inc_categories_menu.html' %}#}
{#</div>#}

<div class="products_list">
    <div class="title clearfix">

        <h2>
            Категория: "{{ category.name|title }}"
        </h2>

    </div>
    {#            <div class="pagination" align="center"><br>#}
    <div class="pagination">
        {# {% if products.has_previous %}#}
        {# <a href="{% url 'products:page' category.pk products.previous_page_number %}"> << </a>#}
        {# {% endif %}#}
        {# <span class="current">#}
        {#  страница {{ products.number }} из {{ products.paginator.num_pages }}#}
        {#  </span>#}
        {# {% if products.has_next %}#}
        {# <a href="{% url 'products:page' category.pk products.next_page_number %}"> >> </a>#}
        {# {% endif %}#}

        {% if products.has_previous %}
            <a href="{% url 'products:category' category.pk %}?p={{ products.previous_page_number }}">
                << </a>
        {% endif %}
        <span class="current">
                        страница {{ products.number }} из {{ products.paginator.num_pages }}
                    </span>
        {% if products.has_next %}
            <a href="{% url 'products:category' category.pk %}?p={{ products.next_page_number }}"> >> </a>
        {% endif %}
        {# <br>#}
        {# <br>#}
    </div>
    <div class="category-products clearfix">

        {% for product in products %}
            <div class="block">
                {# <a> добавление товара          #}
                {#                        <a href="{% url 'basket:add' product.pk %}">#}
                <a href="{% url 'products:product' product.pk %}">
                    {#                            <img src="/media/{{ product.image }}" alt="product">#}
                    <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.description }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>