authapp/urls.py
from django.urls import path

from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<activation_key>/', authapp.veryfy, name='verify')
]

# теперь создаём контроллер в authapp\view

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from mainapp import views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    # path('products/', mainapp.products, name='products'),
    # include all url is mainapp.urls, т.е. в каждом приложении свои URL, namespace='products' - для использования URL
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', mainapp.contact, name='contact'),

    # ссылка на стандартную админку, переименуем в "control/" для добавления своей админки ниже
    # path('admin/', admin.site.urls),
    # path('control/', admin.site.urls),

    # своя админка namespace='admins' - исключаем конфликт
    # с использованием регулярных выражений re_path для сложных проектов
    # re_path(r'^admin/', include('adminapp.urls', namespace='admin'))
    path('admin/', include('adminapp.urls', namespace='admin')),
    # добавляем модуль "social_django"
    path('', include('social_django.urls', namespace='social')),
    # re_path(r'^order/', include('ordersapp.urls', namespace='order')),
    path('order/', include('ordersapp.urls', namespace='order'))
]

# настройка работает локально
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # подгрузка toolbar
# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

authapp/models.py
from datetime import timedelta

from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveSmallIntegerField(verbose_name='возраст', default=18)

    # send message
    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def is_activation_key_expired(self):
        now_date = now() - timedelta(hours=48)
        if now_date <= self.activation_key_expires:
            return False
        return True

class ShopUserProfile(models.Model):
    # choices - вариант выбора заданный жёстко
    MALE = 'M'
    FEMALE = 'W'

    GENDER_CHOICES = {
        (MALE, 'М'),
        (FEMALE, 'Ж'),
    }

    # Связь один к одному, уникальный, не нулевой "False",
    user = models.OneToOneField(ShopUser, unique=True, null=False, db_index=True, on_delete=models.CASCADE)
    tag_line = models.CharField(verbose_name='теги', max_length=128, blank=True)
    about_me = models.TextField(verbose_name='о себе', max_length=512, blank=True)
    gender = models.CharField(verbose_name='пол', max_length=1, choices=GENDER_CHOICES, blank=True)

    # сигнал(post_save) - действие с оъектом
    # sender - кто прислал нам сигнал, instance - объект, created
    # сигнал на создание
    @receiver(post_save, sender=ShopUser)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            ShopUserProfile.objects.create(user=instance)

    # сигнал на обновление
    @receiver(post_save, sender=ShopUser)
    def save_user_profile(sender, instance, **kwargs):
        instance.shopuserprofile.save()

authapp/forms.py
import hashlib
import random

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from authapp.models import ShopUser, ShopUserProfile


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        # Раскладываем словарь, form-control - от bootstrap
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")
        return data

    def clean_email(self):
        data = self.cleaned_data['email']

        # для проектов с низкой нагрузкой !>й
        # if ShopUser.objects.filter(email=data).count() > 0:
        #     f"""select count(*) from authapp_shopuser where email={data}"""
        #     pass # raise ...
        # f"""select count(1) from authapp_shopuser where email={data}"""

        # users_emails = ShopUser.objects.values_list('email', flat=True)
        # users_emails = list(ShopUser.objects.values_list('email', flat=True))
        # if data in users_emails: из базы
        if ShopUser.objects.filter(email=data).exists():
            raise forms.ValidationError("Email exists")
        return data

    def save(self):
        '''Переопределяем метод save, для того чтоб пользователь не мог авторизоватся пока не подтвердит
         свою личность по e-mail рассылке'''
        user = super().save()
        user.is_active = False

        # salt - соль
        salt = hashlib.sha1(str(random.random()).encode('utf8')).hexdigest()[:6]
        user.activation_key = hashlib.sha1((user.email + salt).encode('utf8')).hexdigest()

        user.save()
        return user


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'email', 'age', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                # HiddenInput() - прячем поле с паролем:
                field.widget = forms.HiddenInput()

    def clean_age(self):
        # self.cleaned_data['age'] - лежит то, что нам передал пользователь
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")
        return data

    # def clean_email(self):
    #     data = self.cleaned_data['email']
    #     # exists из SQL
    #     if ShopUser.objects.filter(email=data).exists():
    #         raise forms.ValidationError("Email exists")
    #     return data

class ShopUserProfileEditForm(forms.ModelForm):
    class Meta:
        model = ShopUserProfile
        fields = ('tag_line', 'about_me', 'gender')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            # if field_name == 'password':
            #     # HiddenInput() - прячем поле с паролем:
            #     field.widget = forms.HiddenInput()

    # def avatar(self):
    #     # data = self.avatar['']
    #     user.avatar

authapp/views.py
from django.conf import settings
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm, ShopUserProfileEditForm

# Create your views here.
from authapp.models import ShopUser


# @csrf_exempt
def login(request):
    title = 'вход'
    # POST - при отправке форм, авторизации
    # login_form = ShopUserLoginForm(data=request.POST)
    login_form = ShopUserLoginForm(data=request.POST or None)

    # http://127.0.0.1:8000/auth/login/?next=/basket/add/5/
    # next = request.GET.get('next', '') - упрощённая запись варианта ниже:
    next = request.GET['next'] if 'next' in request.GET.keys() else ''

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        # При использовании не обязательных полей, можно себя обезопасить передав метод "get"
        # с вторым параметром "None", например "username = request.POST.get('username', None)"
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            # передали next из формы стандартной авторизации в пост запросе скрытого инпута
            if 'next' in request.POST.keys():
                # print('redirect next', request.POST['next'])
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('main'))

    content = {
        'title': title,
        'login_form': login_form,
        'next': next
    }
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


def register(request):
    title = 'регистрация'

    # request.FILES - все поля формы которые относятся к загрузке файлов
    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            # register_form.save()
            user = register_form.save()
            if send_verify_email(user):
                print('success')
            else:
                print('failed')
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm()

    content = {
        'title': title,
        'register_form': register_form
    }
    return render(request, 'authapp/register.html', content)


# @login_required
def edit(request):
    title = 'редактирование'
    if request.method == 'POST':
        # instance=request.user - указывает на тот объект который мы редактируем
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        # Добавим ещё одну форму
        profile_form = ShopUserProfileEditForm(request.POST, instance=request.user.shopuserprofile)
        if edit_form.is_valid() and profile_form.is_valid():
            edit_form.save()
            # profile_form - сохраняется через сигналы, поэтому сохранение тут отсутствует
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        # если GET запрос
        edit_form = ShopUserEditForm(instance=request.user)
        profile_form = ShopUserProfileEditForm(instance=request.user.shopuserprofile)

    content = {
        'title': title,
        'edit_form': edit_form,
        'profile_form': profile_form
    }
    return render(request, 'authapp/edit.html', content)


def send_verify_email(user):
    verify_link = reverse('auth:verify', args=[user.email, user.activation_key])

    # title = f'Подтверждение учетной записи {user.username}'
    subject = f'Подтверждение учетной записи {user.username}'

    # message = f'Для подтверждения учетной записи {user.username} на портале {settings.DOMAIN_NAME}\
    #  перейдите по ссылке:\n{settings.DOMAIN_NAME}\n{verify_link}'

    # в verify_link допишется "/"
    message = f'Ссылка для активации: {settings.BASE_URL}{verify_link}'

    # return send_mail(title, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=False)
    #          Тема             сообщение   от кого               кому список   флаг ошибки
    return send_mail(subject, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=True)


# def veryfy(request, email, activation_key):
#     user = ShopUser.objects.get(email=email)
#     if user.activation_key == activation_key and not user.is_activation_key_expired():
#         user.is_active = True
#         # для запрета повторных активаций пользователя "user.activation_key = ''"
#         user.activation_key = ''
#         user.save()
#         # Если с пользователем всё хорошо, то логиним, если нет, то анонимный пользователь
#         # не попадает в это условие и видит текст на странице "verification.html"
#         auth.login(request, user)
#     return render(request, 'authapp/verification.html')

def veryfy(request, email, activation_key):
    try:
        user = ShopUser.objects.get(email=email)
        if user.activation_key == activation_key and not user.is_activation_key_expired():
            user.is_active = True
            # для запрета повторных активаций пользователя "user.activation_key = ''"
            user.activation_key = ''
            user.save()
            # Если с пользователем всё хорошо, то логиним, если нет, то анонимный пользователь
            # не попадает в это условие и видит текст на странице "verification.html"
            auth.login(request, backend=user)
        return render(request, 'authapp/verification.html')

    except Exception as err:
        print(f'error activation user: {err.args}')

    return HttpResponseRedirect(reverse('main'))

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="container">
    <div class="login">
        <div class="h2 text-center head">
            Вход в систему
        </div>
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block content %}
    <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post"
          enctype="multipart/form-data">
        {% csrf_token %}
        {{ edit_form.as_p }}
        {{ profile_form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
{#    <button class="btn btn-round form-control last">#}
    <button class="btn btn-link form-control last">
        <a href="{% url 'main' %}">
            на главную
        </a>
    </button>
    <div class="user_avatar">
        <img src="/media/{{ user.avatar }}">
    </div>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block content %}
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
        {#        {% csrf_token %} - защита от фишинга и прочего #}
        {% csrf_token %}
        {#        стандартная авторизация прячет инпут в поле "next", для считывания его в пост запросе authapp\views.py #}
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}">
        {% endif %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="войти"/>
    </form>
    <br>
    {#    <button class="btn btn-round form-control">#}
    <button class="btn btn-link form-control">
        <a href="{% url 'auth:register' %}">
            зарегистрироваться
        </a>
    </button>
    <button class="btn btn-round form-control">
        <a href="{% url 'social:begin' 'vk-oauth2' %}?next=/">
            Вход через ВКонтакте
        </a>
    </button>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block content %}
{#    enctype="multipart/form-data" - указывает обработчику что мы отправляем ещё и файлы, #}
{#    без этой настройки контроллер файлы не увидит #}
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {#        {% csrf_token %} - защита от фишинга и прочего #}
        {% csrf_token %}
{#        {{ login_form.as_p }}#}
        {{ register_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="регистрация"/>
    </form>
    <br>
    {#    <button class="btn btn-round form-control">#}
    <button class="btn btn-link form-control">
        <a href="{% url 'auth:login' %}">
            вход
        </a>
    </button>
{% endblock %}

authapp/templates/authapp/verification.html
{% extends 'authapp/base.html' %}

{% block content %}
    {#    {% if user.is_authenticated %}#}
    {% if user.activation_key %}
        <h3>Поздравляем!</h3>
        <p>Пользователь {{ user.username }} был успешно активирован!</p>
    {% else %}
        <h3>Увы :(</h3>
        <p>Активация не пройдена</p>
    {% endif %}
    <br>
    <button class="btn btn-round form-control">
        <a href="{% url 'main' %}" class="">на главную</a>
    </button>
{% endblock %}