adminapp/urls.py
from django.urls import path
from adminapp import views as adminapp

# с версии 2.0 app_name
app_name = 'adminapp'

urlpatterns = [
    # CRUD
    path('users/create/', adminapp.user_create, name='user_create'),
    # path( 'users/read/' , adminapp.users, name= 'users' ),
    # path('users/read/', adminapp.users, name='users_read'),
    # path('users/read/', adminapp.user_read, name='user_read'),
    # path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/read/', adminapp.UsersListView.as_view(), name='user_read'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    # path('users/update/<int:pk>/', adminapp.UsersUpdateView, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    # path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    # path( 'categories/read/' , adminapp.categories, name= 'categories' ),
    # path('categories/read/', adminapp.categories, name='category_read'),
    path('categories/read/', adminapp.ProductCategoriesListView.as_view(), name='category_read'),
    # path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    # path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    # path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    # Первый выводит список продуктов в категории
    # path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/category/<int:pk>/', adminapp.ProductListView.as_view(), name='products'),
    # а второй — страницу выбранного продукта
    # path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    # path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    # path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path

from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<activation_key>/', authapp.veryfy, name='verify')
]

# теперь создаём контроллер в authapp\view

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from mainapp import views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    # path('products/', mainapp.products, name='products'),
    # include all url is mainapp.urls, т.е. в каждом приложении свои URL, namespace='products' - для использования URL
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', mainapp.contact, name='contact'),

    # ссылка на стандартную админку, переименуем в "control/" для добавления своей админки ниже
    # path('admin/', admin.site.urls),
    # path('control/', admin.site.urls),

    # своя админка namespace='admins' - исключаем конфликт
    # с использованием регулярных выражений re_path для сложных проектов
    # re_path(r'^admin/', include('adminapp.urls', namespace='admin'))
    path('admin/', include('adminapp.urls', namespace='admin')),
    # добавляем модуль "social_django"
    path('', include('social_django.urls', namespace='social')),
    # re_path(r'^order/', include('ordersapp.urls', namespace='order')),
    path('order/', include('ordersapp.urls', namespace='order'))
]

# настройка работает локально
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # подгрузка toolbar
# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms

from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser

# получаем форму из authapp.forms для редактировани пользователя
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    # добавление дополнительного поля при редактировании категории в админке, initial=0 - по умолчанию
    discount = forms.IntegerField(label='скидка', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = ProductCategory
        # Вместо атрибута разрешенных полей «fields» задаем «exclude» - кортеж с исключенными из отображения полями.
        # fields = '__all__'
        exclude = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.db import connection
from django.db.models import F
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from adminapp.forms import ShopUserAdminEditForm, ProductEditForm, ProductCategoryEditForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    title = 'пользователи/создание'
    # GET - просто отобразить, а POST - обработать форму
    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)
        # user_form = ShopUserAdminEditForm(request.POST, request.FILES)

        if user_form.is_valid():
            user_form.save()
            # reverse - генерируем адрес видимый в строке
            # return HttpResponseRedirect(reverse('admin:users'))
            return HttpResponseRedirect(reverse('adminapp:user_reads'))
    else:
        user_form = ShopUserRegisterForm()
        # user_form = ShopUserAdminEditForm()

    content = {
        'title': title,
        'update_form': user_form
        # 'form': user_form
    }

    return render(request, 'adminapp/user_update.html', content)


# # def users(request):
# @user_passes_test(lambda u: u.is_superuser)
# def user_read(request):
#     title = 'админка/пользователи'
#     users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
#     content = {
#         'title': title,
#         'objects': users_list
#     }
#     return render(request, 'adminapp/users.html', content)

# модель Class Based Views(CBV)
class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        # метод dispatch отвечает за контроль авторизации, но только при
        # @method_decorator(user_passes_test(lambda u: u.is_superuser))
        return super().dispatch(*args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    title = 'пользователи/редактирование'

    edit_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        edit_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)
        # user_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)
        if edit_form.is_valid():
            # if user_form.is_valid():
            edit_form.save()
            # user_form.save()
            # return HttpResponseRedirect(reverse('admin:user_update', args=[edit_user.pk]))
            # редиректим на список польлователей
            # return HttpResponseRedirect(reverse('adminapp:user_update', args=[edit_user.pk]))
            return HttpResponseRedirect(reverse('adminapp:user_read'))
    else:
        # генерируем такую же форму, но без переданных данных о странице
        edit_form = ShopUserAdminEditForm(instance=edit_user)
        # user_form = ShopUserAdminEditForm(instance=edit_user)

    content = {
        'title': title,
        'update_form': edit_form
        # 'form': user_form
    }

    return render(request, 'adminapp/user_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    title = 'пользователи/удаление'
    # фильтрация pk=pk
    # user = get_object_or_404(ShopUser, pk=pk)
    user_item = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        # блок проверки удаления и восстановления пользователя
        if user_item.is_active:
            # вместо удаления лучше сделаем неактивным
            user_item.is_active = False
        else:
            user_item.is_active = True
        # user.delete()
        user_item.save()
        return HttpResponseRedirect(reverse('adminapp:user_read'))

    content = {
        'title': title,
        # шаблонная переменная
        'user_to_delete': user_item
    }

    return render(request, 'adminapp/user_delete.html', content)


# @user_passes_test(lambda u: u.is_superuser)
# def categories(request):
#     title = 'админка/категории'
#
#     categories_list = ProductCategory.objects.all().order_by('-is_active')
#
#     content = {
#         'title': title,
#         'objects': categories_list
#     }
#
#     return render(request, 'adminapp/categories.html', content)

# модель Class Based Views(CBV) категории
# class CategoriesListView(ListView):
class ProductCategoriesListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'

    # template_name = 'adminapp/category_update.html'
    # success_url = reverse_lazy('adminapp:product_read')
    # object_list = ProductCategory.objects.all().order_by('-is_active')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории'
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        # метод dispatch отвечает за контроль авторизации, но только при
        # @method_decorator(user_passes_test(lambda u: u.is_superuser))
        return super().dispatch(*args, **kwargs)


# @user_passes_test(lambda u: u.is_superuser)
# def category_create(request):
#     title = 'категория/создание'
#     # GET - просто отобразить, а POST - обработать форму
#     if request.method == 'POST':
#         user_form = ProductCategoryEditForm(request.POST, request.FILES)
#         # user_form = ProductCategory(request.POST, request.FILES)
#         # user_form = ShopUserAdminEditForm(request.POST, request.FILES)
#
#         if user_form.is_valid():
#             user_form.save()
#             # reverse - генерируем адрес видимый в строке
#             # return HttpResponseRedirect(reverse('admin:users'))
#             return HttpResponseRedirect(reverse('adminapp:category_read'))
#     else:
#         user_form = ProductCategoryEditForm()
#         # user_form = ProductCategory()
#         # user_form = ShopUserAdminEditForm()
#
#     content = {
#         'title': title, 'update_form': user_form
#         # 'form': user_form
#     }
#
#     return render(request, 'adminapp/category_create.html', content)

# модель Class Based Views(CBV) для создания категории
class ProductCategoryCreateView(CreateView):
    model = ProductCategoryEditForm
    template_name = 'adminapp/category_update.html'
    # success_url = '/admin/categories/' - можно прописать так
    # reverse_lazy - отдаёт инфо по вызову, как yield
    # success_url = reverse_lazy('adminapp:category_create')
    success_url = reverse_lazy('adminapp:product_read')
    # fields = '__all__'
    form_class = ProductCategoryEditForm

    # dispatch
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        # метод dispatch отвечает за контроль авторизации, но только при @method_decorator(user_passes_test(lambda u: u.is_superuser))
        return super().dispatch(*args, **kwargs)


# @user_passes_test(lambda u: u.is_superuser)
# def category_update(request, pk):
#     title = 'категория/редактирование'
#
#     edit_category = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         edit_form = ProductCategoryEditForm(request.POST, instance=edit_category)
#         # user_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)
#         if edit_form.is_valid():
#             # if user_form.is_valid():
#             edit_form.save()
#             # user_form.save()
#             # return HttpResponseRedirect(reverse('admin:user_update', args=[edit_user.pk]))
#             # редиректим на список польлователей
#             # return HttpResponseRedirect(reverse('adminapp:user_update', args=[edit_user.pk]))
#             # return HttpResponseRedirect(reverse('adminapp:user_update', args=[edit_category.pk]))
#             return HttpResponseRedirect(reverse('adminapp:category_read'))
#     else:
#         # генерируем такую же форму, но без переданных данных о странице
#         edit_form = ProductCategoryEditForm(instance=edit_category)
#         # user_form = ShopUserAdminEditForm(instance=edit_user)
#
#     content = {
#         'title': title,
#         'update_form': edit_form
#         # 'form': user_form
#     }
#
#     return render(request, 'adminapp/category_update.html', content)

# модель Class Based Views(CBV) для редактирования категории
class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    # success_url = '/admin/categories/' - можно прописать так
    # reverse_lazy - отдаёт инфо по вызову, как yield
    success_url = reverse_lazy('adminapp:category_read')
    # success_url = reverse_lazy('adminapp:product_read')
    # fields = '__all__'
    form_class = ProductCategoryEditForm

    # def get_queryset(self):
    #     return get_object_or_404(self.model, pk=self.kwargs['pk'])
    #
    # def get_context_data(self, **kwargs):
    #     self.get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/редактирование'

        return context

    def form_valid(self, form):
        # это не совсем правильный пример с т.з. бизнес логики нельзя просто взять и переписать все цены
        # для этого лучше использовать поле в модельке
        if 'discount' in form.cleaned_data:

adminapp/templates/adminapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>
        {#        {% if title %}{{ title|title }} - {% endif %}Мой магазин#}
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    {% endblock %}
</head>
<body>

<div class="admin_container">
    <div class="h2 text-center head">
        Админка
    </div>
{#    {% block menu %}#}
    <div class="admin_menu">
        {% include 'adminapp/includes/inc_menu.html' %}
    </div>
{#    {% endblock %}#}
    {#    <div class="container">#}

    {# блок контента #}
    {% block content %}
    {% endblock %}
    <div class="clr"></div>
</div>

</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="categories_list">
        <button class="new_category">
            <a href= {% url 'adminapp:category_create' %}>
                {#            <a href="{% url 'admin:category_create' %}">#}
                новая категория
            </a>
        </button>
{#        {% for object in objects %}#}
        {% for object in object_list %}
            <div class="category_record {% if not object.is_active %}not_active{% endif %}">
                {#                {% if category_to_delete.is_active %}#}
                <div class="category_name">
                    {{ object.name|title }}
                </div>
                <div class="category_actions">
                    <button>
                        <a href= {% url 'adminapp:products' object.pk %}>
                            товары категории
                        </a>
                    </button>
                    {#                    <button>#}
                    {#                        <a href= {% url 'adminapp:category_update' object.pk %}>#}
                    {#                            редактировать#}
                    {#                        </a>#}
                    {#                    </button>#}
                    {#                    <button>#}
                    {#                        <a href= {% url 'adminapp:category_delete' object.pk %}>#}
                    {#                            удалить#}
                    {#                        </a>#}
                    {#                    </button>#}
                    <button>

                        <a href= {% url 'adminapp:category_update' object.pk %}>
                            редактировать
                        </a>
                    </button>
                    <button>
                        {% if object.is_active %}
                            <a href="{% url 'adminapp:category_delete' object.pk %}">
                                удалить
                            </a>
                        {% else %}
                            <a href="{% url 'adminapp:category_delete' object.pk %}">
                                восстановить
                            </a>
                        {% endif %}
                    </button>
                </div>
                <div class="category_desc">
                    {{ object.description|title }}
                </div>
                {#            {% endif %}#}
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="user_delete">
    {% if category_to_delete.is_active %}
        Уверены, что хотите удалить <b>{{ category_to_delete.name }}</b>
    {% else %}
        Уверены, что хотите восстановить <b>{{ category_to_delete.name }}</b>
    {% endif %}
{#    {% if category_to_delete.name %}#}
{#        <b>{{ category_to_delete.name|title }}</b>#}
        {# {% if user_to_delete.last_name %}#}
        {#  {{ user_to_delete.last_name|title }}#}
{#    {% endif %}#}
{#    {% endif %}#}

    {# Кнопка удалить в форме с пост запросом #}
    <form action="{% url 'adminapp:category_delete' category_to_delete.pk %}"
          method="post">
        {% csrf_token %}
        {# блок проверки удаления и восстановления пользователя #}
        {% if category_to_delete.is_active %}
            <input class="btn btn-danger" type="submit" value="удалить">
        {% else %}
            <input class="btn btn-primary" type="submit" value="восстановить">
        {% endif %}
    </form>
    <button class="btn btn-success">
        <a href="{% url 'adminapp:category_read' %}">
            Отмена
        </a>
    </button>
</div>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    {#    <div class="login">#}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {#  ссылка на переменную в контролере 183стр. #}
{#            {{ update_form.as_p }}#}
            {{ form.as_p }}

            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            {#        <a href="{% url 'admin:users' %}">#}
{#            <a href="{% url 'adminapp:category_read' category.pk %}">#}
            <a href="{% url 'adminapp:category_read' %}">
{#            <a href="{% url 'adminapp:products' object.category.pk %}">#}
                к списку категорий
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="category_delete">
{#    {% if object.is_active %}#}
    {% if object.is_active %}
        Уверены, что хотите удалить продукт <b>{{ object.name }}</b>
    {% else %}
        Уверены, что хотите восстановить продукт <b>{{ object.name }}</b>
    {% endif %}

    {# Кнопка удалить в форме с пост запросом #}
    <form action="{% url 'adminapp:product_delete' object.pk %}"
          method="post">
        {% csrf_token %}
        {# блок проверки удаления и восстановления пользователя #}
        {% if object.is_active %}
            <input class="btn btn-danger" type="submit" value="удалить">
        {% else %}
            <input class="btn btn-primary" type="submit" value="восстановить">
        {% endif %}
    </form>
    <button class="btn btn-success">
        <a href="{% url 'adminapp:products' object.category.pk %}">
            Отмена
        </a>
    </button>
</div>
{% endblock %}

adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="product_read">
        <div class="product_name">
            Продукт<strong>{{ object.category.name|title }} /
            {{ object.name|title }}</strong>
        </div>
        <img src="/media/{{ object.image|default:'products_images/default.jpg' }}"
             alt="{{ object.name }}">
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
            <b>в каталоге</b>
            <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
            <p>
                <button>
{#                    <a href={% url 'adminapp:product_update' object.pk %}>#}
                    <a href={% url 'adminapp:product_update' object.pk %}>
                        редактировать
                    </a>
                </button>
            </p>
            <p>
                <button>
                    <a href={% url 'adminapp:product_delete' object.pk %}>
                        удалить
                    </a>
                </button>
            </p>
            <p>
                <button>
                    <a href={% url 'adminapp:products' object.category.pk %}>
                        назад
                    </a>
                </button>
            </p>
        </div>
        <div class="product_desc">
            <b>краткая информация</b>
            <p>{{ object.short_desc }}</p>
            <br><br>
            <b>подробная информация</b>
            <p>{{ object.description }}</p>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    {#    <div class="login">#}
    <div class="new_category_form">
        <div class="users_list">
            <form class="form-horizontal" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {#  ссылка на переменную в контролере 183стр. #}
                {#  {{ update_form.as_p }}#}
                {# из CBV всегда передаётся обект form #}
                {{ form.as_p }}

                <input class="form-control" type="submit" value="сохранить">
            </form>
            <button class="btn btn-round form-control last">
                {#        <a href="{% url 'admin:users' %}">#}
{#                <a href="{% url 'adminapp:product_read' object.category.pk %}">#}
{#                <a href="{% url 'adminapp:products' object.category.pk %}">#}
                <a href="{% url 'adminapp:products' category.pk %}">
                    к списку продуктов
                </a>
            </button>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{# подгрузка шаблонного фильтра #}
{% load my_tags %}

{% block content %}
    <div class="products_list">
        <button class="new_product">
            {#            <a href="{% url 'admin:product_create' category.pk %}">#}
            <a href="{% url 'adminapp:product_create' category.pk %}">новый продукт</a>
        </button>
        <br>
        <div class="pagination" >
            {% if page_obj.has_previous %}
                <a href="{% url 'adminapp:products' category.pk %}?page={{ page_objt.previous_page_number }}"> << </a>
            {% endif %}
            <span class="current">
                        страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                    </span>
            {% if page_obj.has_next %}
                <a href="{% url 'adminapp:products' category.pk %}?page={{ page_obj.next_page_number }}"> >> </a>
            {% endif %}
            <br>
            <br>
        </div>
        {#        {% for object in objects %}#}
        {% for object in object_list %}
            <div class="product_record {% if not object.is_active %}not_active{% endif %}">
                {#                <img src="/media/{{ object.image|default:'products_images/default.jpg' }}"#}
                <img src="{{ object.image|media_folder_products }}"
                     alt="{{ object.name }}">
                <div class="product_name">
                    {{ object.name|title }}
                </div>
                <div class="product_actions">
                    <button>
                        <a href= {% url 'adminapp:product_read' object.pk %}>
                            подробнее
                        </a>
                    </button>
                    <button>
                        <a href= {% url 'adminapp:product_update' object.pk %}>
                            редактировать
                        </a>
                    </button>
                    <button>
                        {#                      {# Кнопка восстановить #}
                        {% if object.is_active %}
                            <a href="{% url 'adminapp:product_delete' object.pk %}">удалить</a>
                        {% else %}
                            <a href="{% url 'adminapp:product_delete' object.pk %}">восстановить</a>
                        {% endif %}
                    </button>
                </div>
                <div class="summary">
                    <b>цена</b>
                    <p>{{ object.price }} руб</p>
                    <b>количество</b>
                    <p>{{ object.quantity }}</p>
                </div>
                <div class="product_desc">
                    {{ object.short_desc|title }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{# подгрузка шаблонного фильтра #}
{% load my_tags %}

{% block content %}
    <div class="users_list">
        <button class="new_user">
            {#            <a href="{% url 'admin:user_create' %}">#}
            <a href="{% url 'adminapp:user_create' %}">
                новый пользователь
            </a>
        </button>
{#        {% for object in objects %}#}
        {% for object in object_list %}
            <div
                    class="user_record {% if not object.is_active %}not_active{% endif %}">
{#                <img src="/media/{{ object.avatar|default:'users_avatars/default.png' }}"#}
                <img src="{{ object.avatar|media_folder_users }}"
                     alt="{{ object.username }}">
                <div class="user_role">
                    {% if object.is_superuser %}
                        администратор
                    {% else %}
                        пользователь
                    {% endif %}
                    <button>
                        {#                        <a href="{% url 'admin:user_update' object.pk %}">#}
                        <a href="{% url 'adminapp:user_update' object.pk %}">редактировать</a>
                    </button>
                    <button>
                        {# Кнопка восстановить #}
                        {% if object.is_active %}
                        {# <a href="{% url 'admin:user_delete' object.pk %}">#}
                        <a href="{% url 'adminapp:user_delete' object.pk %}">удалить</a>
                        {% else %}
                        <a href="{% url 'adminapp:user_delete' object.pk %}">восстановить</a>
                        {% endif %}
                    </button>
                </div>
                <div class="user_name">
                    <p><strong>{{ object.username }}</strong></p>
                    <p>
                        {# если у пользователя есть имя, то выводим его #}
                        {% if object.first_name %}
                            <b>{{ object.first_name|title }}</b>
                            {% if object.last_name %}
                                <p>{{ object.last_name|title }}</p>
                            {% endif %}
                        {% endif %}
                    </p>
                </div>
                <div class="user_age">
                    age:<br>
                    {{ object.age }} лет
                </div>
                <div class="user_email">
                    email:<br>
                    {{ object.email }}
                </div>
                <div class="user_lastlogin">
                    logged:<br>
                    {{ object.last_login|date:"d-m-Y" }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}