authapp/urls.py
from django.urls import path

from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<activation_key>/', authapp.veryfy, name='verify')
]

# теперь создаём контроллер в authapp\view

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from mainapp import views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    # path('products/', mainapp.products, name='products'),
    # include all url is mainapp.urls, т.е. в каждом приложении свои URL, namespace='products' - для использования URL
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', mainapp.contact, name='contact'),

    # ссылка на стандартную админку, переименуем в "control/" для добавления своей админки ниже
    # path('admin/', admin.site.urls),
    # path('control/', admin.site.urls),

    # своя админка namespace='admins' - исключаем конфликт
    # с использованием регулярных выражений re_path для сложных проектов
    # re_path(r'^admin/', include('adminapp.urls', namespace='admin'))
    path('admin/', include('adminapp.urls', namespace='admin')),
    # добавляем модуль "social_django"
    path('', include('social_django.urls', namespace='social')),
    # re_path(r'^order/', include('ordersapp.urls', namespace='order')),
    path('order/', include('ordersapp.urls', namespace='order'))
]

# настройка работает локально
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # подгрузка toolbar
# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

ordersapp/urls.py
import ordersapp.views as ordersapp

from django.urls import path, re_path

app_name = 'ordersapp'

urlpatterns = [
    # re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    path('', ordersapp.OrderListView.as_view(), name='orders_list'),
    # re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    path('create/', ordersapp.OrderCreateView.as_view(), name='orders_create'),
    # re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    path('read/<int:pk>/', ordersapp.OrderDetailView.as_view(), name='orders_detail'),
    # re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    path('update/<int:pk>/', ordersapp.OrderUpdateView.as_view(), name='orders_update'),
    # re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),
    path('delete/<int:pk>/', ordersapp.OrderDeleteView.as_view(), name='orders_delete'),

    # re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),
    path('forming/complete/<int:pk>/', ordersapp.order_forming_complete, name='orders_forming_complete'),

    re_path(r'^product/(?P<pk>\d+)/price/$', ordersapp.get_product_price)

]

ordersapp/models.py
from django.conf import settings
from django.db import models


# Create your models here.
from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    # ORDER_STATUSES
    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # auto_now_add=True - заполняется при создании записи
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    # auto_now=True - фиксация даты при любых изменениях записи
    updated = models.DateTimeField(verbose_name='изменён', auto_now=True)
    # choices - выбор, max_length=3 - это PROCEEDED = 'PRD'
    status = models.CharField(verbose_name='статус', max_length=3, choices=ORDER_STATUS_CHOICES, default=FORMING)
    # флаг удаления, по умолчанию активен
    is_active = models.BooleanField(db_index=True, verbose_name='активен', default=True)

    class Meta:
        # сортировка для CBV, по умолчанию от более новых к старым заказам (кортеж,):
        ordering = ('-created',)
        # имя класса в единственном числе:
        verbose_name = 'заказ'
        # имя класса во множественном числе:
        verbose_name_plural = 'заказы'

    def __str__(self):
        # return 'Текущий заказ: {}'.format(self.id)
        return f'Текущий заказ: {self.pk}'

    def get_total_quantity(self):
        # при помощи метода «select_related()» находим все элементы заказа
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        # return sum(list(map(lambda x: x.quantity * x.product.price, items)))
        return sum(list(map(lambda x: x.get_product_cost(), items)))

    def get_summary(self):
        items = self.orderitems.select_related()
        return {
            'total_cost': sum(list(map(lambda x: x.quantity * x.product.price, items))),
            'total_quantity': sum(list(map(lambda x: x.quantity, items)))
        }

    # переопределяем метод, удаляющий объект is_active
    def delete(self):
        for item in self.orderitems.select_related():
            # и корректируем количество продуктов на складе (возвращаем на склад)
            item.product.quantity += item.quantity
            item.product.save()
        self.is_active = False
        self.save()


class OrderItem(models.Model):
    '''Раскладываем корзину заказов на отдельные продукты'''
    # от каждого объекта через точку сможем получить доступ к "orderitems"
    order = models.ForeignKey(Order, related_name="orderitems", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        # Количество и продукт теперь в OrderItem, поэтому сдесь делаем подсчёт стоимости
        return self.product.price * self.quantity

ordersapp/forms.py
from django import forms

from mainapp.models import Product
from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        # исключаем поле пользователя из отображения, поскольку с этим работает пользователь
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        # super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            # field.help_text = ''


class OrderItemForm(forms.ModelForm):
    # расширяем поля. Ставим "required=False" чтоб форма не требовала заполнения поля
    price = forms.CharField(label='Цена', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        # super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            # field.help_text = ''
        # Убираем неактивные продукты с формы
        # self.fields['product'].queryset = Product.get_items()
        self.fields['product'].queryset = Product.get_items().select_related()

ordersapp/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from basketapp.models import Basket
from mainapp.models import Product
from ordersapp.forms import OrderForm, OrderItemForm
from ordersapp.models import Order, OrderItem


class OrderListView(ListView):
    model = Order

    def get_queryset(self):
        '''Фильтруем заказы по текущему пользователю'''
        return Order.objects.filter(user=self.request.user).select_related()

    # @method_decorator(login_required())
    # def dispatch(self, *args, **kwargs):
    #     return super(ListView, self).dispatch(*args, **kwargs)


# OrderItemsCreate
class OrderCreateView(CreateView):
    model = Order
    success_url = reverse_lazy('ordersapp:orders_list')
    # Выводит поле выбора статуса
    # form_class = OrderForm
    fields = []

    def get_context_data(self, **kwargs):
        # data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        data = super().get_context_data(**kwargs)

        # FormSet - набор форм, зависит от основной формы и ссылается на FormSet
        # OrderFormSet - просто переменная. Осн-я, второст-я модель,  форма,      количество строк для вывода в форму
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            # Если else, собираем formset пустой
            # basket_items = Basket.get_items(self.request.user)
            # Выбираем все корзины пользователя
            basket_items = Basket.objects.filter(user=self.request.user).select_related()
            if len(basket_items):
                # Переносим в заказ, extra=len(basket_items)
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_items))
                formset = OrderFormSet()
                # form - хранит инфо о свободных местах из extra=len(basket_items)
                for num, form in enumerate(formset.forms):
                    # заполняем данными, для 5 корзин - 5 заказов
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    # заполняем поле цена указанное в forms
                    form.initial['price'] = basket_items[num].product.price

            else:
                formset = OrderFormSet()
            # после заполнения и передачи на обработку нам эти данные не нужны, удаляем
            # basket_items.delete()

        # передаём formset дальше
        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        '''Сохраняем formset вызываемый при POST запросе к контроллеру OrderCreateView'''
        # выбираем весь контекст, набор форм и пользовательский ввод
        context = self.get_context_data()
        orderitems = context['orderitems']

        # исключаем возможность ввода ошибочной информации от пользователя при передаче формы,
        # если is_valid - false, orderitems не сохраняется
        # для избежания этого оборачиваем код в атомарную(не делима) транзакцию к БД
        with transaction.atomic():
            # а тут delete() применяем к QuerySet с корзинами пользователя
            Basket.get_items(self.request.user).delete()
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                # instance - ссылка на родительский класс
                orderitems.instance = self.object
                orderitems.save()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()
        return super().form_valid(form)


# OrderRead
class OrderDetailView(DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = 'заказ/просмотр'
        return context


class OrderUpdateView(UpdateView):
    model = Order
    success_url = reverse_lazy('ordersapp:orders_list')
    # Выводит поле выбора статуса
    # form_class = OrderForm
    fields = []

    def get_context_data(self, **kwargs):
        # data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        data = super().get_context_data(**kwargs)

        # FormSet - набор форм, зависит от основной формы и ссылается на FormSet
        # OrderFormSet - просто переменная. Осн-я, второст-я модель,  форма,      количество строк для вывода в форму
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            # data['orderitems'] = OrderFormSet(self.request.POST, instance=self.object)
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:
            # data['orderitems'] = OrderFormSet(instance=self.object)
            formset = OrderFormSet(instance=self.object)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price
            # data['orderitems'] = formset
        # передаём formset дальше
        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        '''Сохраняем formset вызываемый при POST запросе к контроллеру OrderCreateView'''
        # выбираем весь контекст, набор форм и пользовательский ввод
        context = self.get_context_data()
        orderitems = context['orderitems']

        # исключаем возможность ввода ошибочной информации от пользователя при передаче формы,
        # если is_valid - false, orderitems не сохраняется
        # для избежания этого оборачиваем код в атомарную(не делима) транзакцию к БД
        with transaction.atomic():
            self.object = form.save()
            if orderitems.is_valid():
                # instance - ссылка на родительский класс
                orderitems.instance = self.object
                orderitems.save()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()
        return super().form_valid(form)


class OrderDeleteView(DeleteView):
    # Метод удаления переопределён в модели Order, поэтому дополнительно ничего не пишем
    model = Order
    success_url = reverse_lazy('ordersapp:orders_list')


# совершение покупки
def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('ordersapp:orders_list'))

# сигналы, можно на одну функцию 2 сигнала
@receiver(pre_save, sender=Basket)
@receiver(pre_save, sender=OrderItem)
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    '''Обновление при сохранении'''
    # one случай
    # если у нас поля которые были обновлены 'quantity' or 'product', то мы должны понять, это создание или обновление
    # когда идёт pre_save мы ещё ничего не сохранили в базу, т.к. не сохранили у нас нет "pk" а запись находится
    # в instance значит делаем проверку "if"
    # if update_fields in  :
    if update_fields is 'quantity' or 'product':
        # default instance.pk = None
        if instance.pk:
            instance.product.quantity -= instance.quantity - sender.get_item(instance.pk).quantity
        else:
            # если продукт новый
            instance.product.quantity -= instance.quantity
        instance.product.save()

# сигналы
@receiver(pre_delete, sender=Basket)
@receiver(pre_delete, sender=OrderItem)
def product_quantity_update_delete(sender, instance, **kwargs):
    '''Обновление при удалении'''
    # two случай
    instance.product.quantity += instance.quantity
    instance.product.save()


def get_product_price(request, pk):
    if request.is_ajax():
        product = Product.objects.filter(pk=int(pk)).first()
        if product:
            # возврат данных в виде "JsonResponse" для удачной сериализации в дальнейшем
            return JsonResponse({'price': product.price})
        else:
            return JsonResponse({'price': 0})

ordersapp/templates/ordersapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% if title %}{{ title|title }} - {% endif %}Мой магазин
        {# {{ title|capfirst }}#}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
{#        <script src="{% static 'js/main_scripts.js' %}"></script>#}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/jquery.formset.js' %}"></script>
        <script src="{% static 'js/orders_script.js' %}"></script>
    {% endblock %}
</head>
<body>
{% block menu %}
{#    {% include 'mainapp/includes/inc_menu.html' %}#}
{% endblock %}
<div class="order_container">

    {# блок контента #}
    {% block content %}
    {% endblock %}
    {#    <div class="clr"></div>#}
</div>
{# блок футера #}
{#{% block footer %}#}
{#    <div class="footer">#}
{#        <div class="clearfix">#}
{#            <div class="text-footer">#}
{#                <h3>контакты</h3>#}
{#            </div>#}
{#            <div class="text-footer">#}
{#                <h3>полезная информация</h3>#}
{#            </div>#}
{#            <div class="text-footer clearfix">#}
{#                <h3>Оставайтесь на связи</h3>#}
{#                <p>Подписаться на новости и рассылки</p>#}
{#                <form>#}
{#                    <input type="email" name="email" placeholder="ваш email">#}
{#                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>#}
{#                </form>#}
{#            </div>#}
{#        </div>#}
{#        <p class="small">&copy; GB {% now "Y" %}</p>#}
{#        <div class="social">#}
{#            <a href="#" class="social1"></a>#}
{#            <a href="#" class="social2"></a>#}
{#            <a href="#" class="social3"></a>#}
{#            <a href="#" class="social4"></a>#}
{#        </div>#}
{#        <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>#}
{#    </div>#}
{#{% endblock %}#}

</body>
</html>

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load static %}
{% block content %}
    <div class="category_delete">
        <div class="h1">Уверены, что хотите удалить?</div>
        {% include 'ordersapp/includes/inc_order_summary.html' %}
        <form action="{% url 'ordersapp:orders_delete' object.pk %}"
              method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'ordersapp:orders_list' %}">отмена</a>
        </button>
    </div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends "ordersapp/base.html" %}
{% load static %}
{% load my_tags %}
{% block content %}
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <div class="basket_list">
        {% for item in object.orderitems.select_related %}
            <div class="basket_record">
                <img class="basket_record_img" src="{{ item.product.image|media_folder_products }}"
                     alt="{{ item.product.short_desc }}">
                <span class="category_name">
                    {{ item.product.category.name }}
                </span>
                <span class="product_name">{{ item.product.name }}</span>
                <span class="product_price">
                    {{ item.product.price }}&nbspруб
                </span>
                <span class="product_quantitiy">
                    x {{ item.quantity }} шт.
                </span>
                <span class="product_cost">
                    = {{ item.get_product_cost }}&nbspруб
                </span>
            </div>
        {% endfor %}
    </div>
    {% include 'ordersapp/includes/inc_order_actions.html' %}
{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{# для шаблонов создания и редактирования #}
{% extends 'ordersapp/base.html' %}
{% load static %}
{#подкл. кэш#}
{% load cache %}

{% block content %}
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <div class="order_form">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <table class="table">
                {{ orderitems.management_form }}
                {% for form in orderitems.forms %}
                    {% if forloop.first %}
                        {# при первом проходе выводим все видимые заголвки, поля#}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                {# <th class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">#}
                                <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                    {{ field.label|capfirst }}
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset_row">
                        {# выводим все видимые значения полей внутри #}
                        {% for field in form.visible_fields %}
                            <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                {% if forloop.first %}
                                    {# выводим при первом проходе все поля, но уже от formset#}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {% if field.name != 'price' %}
                                    {# до кэша: {{ field }}#}
                                    {# {{ field }}#}
                                    {# ---cache#}
                                    {# второй уровень кеширования #}
                                    {% if field.name == 'product' %}
                                        {% cache 3600 orderitemform_product field.value %}
                                            {{ field }}
                                        {% endcache %}
                                    {% else %}
                                        {{ field }}
                                    {% endif %}
                                    {# ---/cache #}
                                {% else %}
                                    {% if field.value %}
                                        {# class="orderitems-0-price" #}
                                        <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">
                                            {{ field.value }}
                                        </span> руб
                                    {% endif %}
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить
            </button>
            {% include 'ordersapp/includes/inc_order_actions.html' %}
        </form>
    </div>
{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block content %}
    <div class="h2 text-center head">
        Ваши заказы,
        {% if user.first_name %}
            {{ user.first_name|title }}
        {% else %}
            Пользователь
        {% endif %}
    </div>
    <table class="table orders_list">
        <thead>
        <tr>
            <th>ID</th>
            <th>Создан</th>
            <th>Обновлен</th>
            <th>Статус</th>
        </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            {% if item.is_active %}
                <tr>
                    <td class="td1 orders_list">{{ item.pk }}</td>
                    <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.get_status_display }}</td>
                    <td>
{#                        <a href="{% url 'ordersapp:order_read' item.pk %}">#}
                        <a href="{% url 'ordersapp:orders_detail' item.pk %}">
                            посмотреть
                        </a>
                    </td>
                    <td>
                        {% if item.status == 'FM' %}
{#                            <a href="{% url 'ordersapp:order_update' item.pk %}">#}
                            <a href="{% url 'ordersapp:orders_update' item.pk %}">
                                редактировать
                            </a>
                        {% endif %}
                    </td>
                    <td>
                        {% if item.status == 'FM' %}
{#                            <a href="{% url 'ordersapp:order_delete' item.pk %}">#}
                            <a href="{% url 'ordersapp:orders_delete' item.pk %}">
                                удалить
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
    <button class="btn btn-default btn-round">
        <a href="{% url 'main' %}">
            на главную
        </a>
    </button>
    <button class="btn btn-default btn-round">
        <a href="{% url 'ordersapp:orders_create' %}">
            новый
        </a>
    </button>
{% endblock %}